config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'couriers#index', as: 'home'

  resources :couriers do 
  	resources :packages
  end


  get 'about' => 'deliveries#about', as:'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
	has_many :packages
	validates :name, presence: true, length: {minimum: 3}
end

app/models/package.rb
class Package < ApplicationRecord
	belongs_to :courier

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
	def index
		@couriers = Courier.all
	end
	def show
		@courier = Courier.find(params[:id])
	end
	def new
		@courier = Courier.new
	end
	def create
		#render plain: params[:courier].inspect
		@courier = Courier.new(courier_params)
		
		if(@courier.save)
		redirect_to @courier
		else 
			render 'new'
		end	
	def edit
		@courier = Courier.find(params[:id])
	end

	def update
		@courier = Courier.find(params[:id])

		if(@courier.update(courier_params))
			redirect_to @courier
		else 
			render 'edit'
		end	
	end
	end
	def destroy
		@courier = Courier.find(params[:id])
		@courier.destroy

		redirect_to couriers_path
		
	end
	private def courier_params
		params.require(:courier).permit(:name,:email)
		
	end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
	def about
		@title = 'This app was created by Andrew Redchenkov';
		@content = 'This is test'
	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
	def create
		@courier = Courier.find(params[:courier_id])
		@package  = @courier.packages.create(package_params)
		redirect_to courier_path(@courier)
	end

	def destroy
		@courier = Courier.find(params[:courier_id])
		@package = @courier.packages.find(params[:id])
		@package.destroy
		redirect_to courier_path(@courier)
	end

	private def package_params
		params.require(:package).permit(:tracking_number, :delivery_status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/edit.html.erb
<h2>Edit Courier Info</h2>
<%= form_for :courier, url: courier_path(@courier), method: :patch do |f| %>
	<% if @courier.errors.any? %>
		<% @courier.errors.full_messages.each do |msg|%>
			<div class='alert alert-danger'><%= msg %> </div>
		<% end %>	
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field(:name, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :email%><br>
		<%= f.text_field(:email, {:class => 'form-control'})%>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>	

app/views/couriers/index.html.erb
<h1>Couriers</h1>
<% @couriers.each do |courier|%>
	<div class="jumbotron">
		<h3><%= courier.name %></h3>
		<p class="lead"><%= courier.email %></p>

		<button class="btn btn-primary" type="button">
  			Packages count: <%= courier.packages.count%> 
  			<span class="badge"></span>
		</button>

		<%= link_to "Details", courier_path(courier), :class => 'btn btn-primary' %>
	</div>
	
<% end %>

app/views/couriers/new.html.erb
<h1>Add Courier</h1>
<%= form_for :courier, url: couriers_path do |f| %>
	<% if @courier.errors.any? %>
		<% @courier.errors.full_messages.each do |msg|%>
			<div class='alert alert-danger'><%= msg %> </div>
		<% end %>	
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field(:name, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :email%><br>
		<%= f.text_field(:email, {:class => 'form-control'})%>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>	

app/views/couriers/show.html.erb
<h2><%= @courier.name %></h2>
<p><%= @courier.email %></p>
<hr>
<%= link_to "Edit", edit_courier_path(@courier), :class => "btn btn-primary" %>

<%= link_to "Delete", courier_path(@courier),
		method: :delete,
		data: {confirm: 'Are you sure?'},
	 	:class => 'btn btn-danger' %>
<hr>
<%= render 'packages/packages' %>
<%= render 'packages/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Firstapp</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   </head>
   <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
         <a class="navbar-brand">Delivery App</a>
         <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
               <li class="navbar-brand"><%= link_to "Home", home_path%></li>
            </ul>
            <ul class="navbar-nav mr-right">
               <li class="navbar-brand"><%= link_to "Add Courier", new_courier_path%></li>
            </ul>
         </div>
      </nav>
      <div class="container">
         <%= yield %>
      </div>
   </body>
</html>